[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "oop_homework"
version = "1.0.0"
description = "Homework on OOP_14.1: classes Product and Category"
authors = [{name = "Denis White", email = "your.email@example.com"}]
dependencies = []

[project.optional-dependencies]
test = ["pytest>=9.0.3"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
